import type { MetadataRoute } from "next";
import { appUrl } from "@/lib/env";

export default function robots(): MetadataRoute.Robots {
  const baseUrl = appUrl();

  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/pricing",
          "/features",
          "/features/*",
          "/solutions",
          "/solutions/*",
          "/blog",
          "/blog/*",
          "/changelog",
          "/about",
          "/contact",
          "/security",
          "/customers",
          "/customers/*",
          "/guides",
          "/guides/*",
          "/careers",
          "/careers/*",
          "/community",
          "/webinars",
          "/press",
          "/resources/templates",
          "/help",
          "/legal/*",
          "/roadmap",
          "/status",
          "/tools",
          "/tools/*",
        ],
        disallow: [
          "/api/",
          "/admin/",
          "/dashboard",
          "/composer",
          "/composer/",
          "/calendar",
          "/queue",
          "/recycling",
          "/analytics",
          "/analytics/",
          "/inbox",
          "/comments",
          "/automations",
          "/media",
          "/studio",
          "/ideas",
          "/trends",
          "/opportunities",
          "/competitors",
          "/templates",
          "/integrations",
          "/reports",
          "/reports/",
          "/insights",
          "/insights/",
          "/agency",
          "/agency/",
          "/referrals",
          "/settings/",
          "/team",
          "/campaigns",
          "/campaigns/",
          "/portal/",
          "/share/",
          "/switch",
          "/onboarding",
          "/login",
          "/signup",
          "/reset",
          "/forgot",
          "/verify",
          "/401",
          "/403",
          "/500",
          "/502",
          "/503",
          "/offline",
          "/maintenance",
        ],
      },
    ],
    sitemap: `${baseUrl.replace(/\/$/, "")}/sitemap.xml`,
  };
}
